import logging
import matplotlib.pyplot as plt
import numpy as np
import pathlib

from packages.logging import get_logger
from packages.logging.decorators import log_function_call

logger = get_logger(__name__)

def plot_2d_results(
        dataset : np.ndarray,
        labels : np.ndarray,
        plot_save_path: pathlib.Path):
    """Plot the results of a model on a 2D-dataset.

    Args:
        dataset (np.ndarray): Dataset of points on a 2D-plane. If there are 
            more than 2 dimensions, only the first 2 will be used to plot the
            results.
        labels (np.ndarray): Labels for all points, generated by the model. Is
            used to color the different points.
        plot_save_path (pathlib.Path): Path where the plot should be saved.
    """
    logger.info(f"Plotting results. Saving plot to {plot_save_path}")
    plt.scatter(
        dataset[:,0], dataset[:,1],
        c=labels,
        alpha=0.75
    )
    plt.savefig(plot_save_path)
    plt.close()